### ISSUE TITLE
Bug Report: cloud-init not working

### ISSUE THREAD

**Issue by gjrtimmer** [Joshua-Riek/ubuntu-rockchip#1211]
### What happened?

I'm running the RockChip server image for my RK1. Now, my issue is that after flashing, I mount the drive with the storage and copy over my own `cloud.cfg` to `/etc/cloud/cloud.cfg`. I also remove `/var/lib/cloud` to ensure that on the first boot, it the cloud-init runs.

However, I do not get the results I was expected. I was expecting that my `ubuntu` user would have the password I provided and that an ansible user was created. However this is not the case.

Anybody any thoughts why on first boot it does not run my cloud init.

After I connect for the first time, then asked to change my password, and actually login for the first time, if I then remove the `/var/lib/cloud` and reboot, the ansible user is created.

Anybody any idea?

This is my cloud-init config, it is a J2 template, because it is send to the node through ssh.
If you want me to post the rendered one, I will.

```yaml
#cloud-config
# Source: https://cloudinit.readthedocs.io/en/latest/reference/base_config_reference.html#example
#
# The top level settings are used as module and base configuration.
# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
  - default
  - name: {{ users.provision }}
    lock_passwd: false
    passwd: "$6$p9zPQA5/WXGxoKdx$yh7CzuS8cP23/nBcsdbjWn/dc8TfhOF57hlziKtDpqJTH2K2me3SBGhEpeFg.X42aUcxT/zW1BbNieKmbcNFo."
    chpasswd: { expire: False }
    gecos: Ansible User
    groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys:
      - {{ lookup('file', '~/.ssh/tpi/{{ prefix }}.ansible.key.pub') }}

chpasswd:
  expire: false

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: true

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false
hostname: {{ inventory_hostname }}

timezone: {{ timezone }}

# The modules that run in the 'init' stage
cloud_init_modules:
  - migrator
  - seed_random
  - bootcmd
  - write_files
  - growpart
  - resizefs
  - disk_setup
  - mounts
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - ca_certs
  - rsyslog
  - users_groups
  - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
  - users_groups
  - wireguard
  - snap
  - ubuntu_autoinstall
  - ssh_import_id
  - keyboard
  - locale
  - set_passwords
  - grub_dpkg
  - apt_pipelining
  - apt_configure
  - ubuntu_pro
  - ntp
  - timezone
  - disable_ec2_metadata
  - runcmd
  - byobu

# The modules that run in the 'final' stage
cloud_final_modules:
  - package_update_upgrade_install
  - fan
  - landscape
  - lxd
  - ubuntu_drivers
  - write_files_deferred
  - puppet
  - chef
  - ansible
  - mcollective
  - salt_minion
  - reset_rmc
  - scripts_vendor
  - scripts_per_once
  - scripts_per_boot
  - scripts_per_instance
  - scripts_user
  - ssh_authkey_fingerprints
  - keys_to_console
  - install_hotplug
  - phone_home
  - final_message
  - power_state_change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
  # This will affect which distro class gets used
  distro: ubuntu
  # Default user name + that default users groups (if added/used)
  default_user:
    name: {{ users.default }}
    passwd: "$6$p9zPQA5/WXGxoKdx$yh7CzuS8cP23/nBcsdbjWn/dc8TfhOF57hlziKtDpqJTH2K2me3SBGhEpeFg.X42aUcxT/zW1BbNieKmbcNFo."
    chpasswd: { expire: False }
    lock_passwd: false
    gecos: Ubuntu
    groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys:
      - {{ lookup('file', '~/.ssh/tpi/{{ prefix }}.ubuntu.key.pub') }}
  network:
    renderers: ['netplan', 'eni', 'sysconfig']
    activators: ['netplan', 'eni', 'network-manager', 'networkd']
  # Automatically discover the best ntp_client
  ntp_client: auto
  # Other config here will be given to the distro class and/or path classes
  paths:
    cloud_dir: /var/lib/cloud/
    templates_dir: /etc/cloud/templates/
  package_mirrors:
    - arches: [i386, amd64]
      failsafe:
        primary: http://archive.ubuntu.com/ubuntu
        security: http://security.ubuntu.com/ubuntu
      search:
        primary:
          - http://%(ec2_region)s.ec2.archive.ubuntu.com/ubuntu/
          - http://%(availability_zone)s.clouds.archive.ubuntu.com/ubuntu/
          - http://%(region)s.clouds.archive.ubuntu.com/ubuntu/
        security: []
    - arches: [arm64, armel, armhf]
      failsafe:
        primary: http://ports.ubuntu.com/ubuntu-ports
        security: http://ports.ubuntu.com/ubuntu-ports
      search:
        primary:
          - http://%(ec2_region)s.ec2.ports.ubuntu.com/ubuntu-ports/
          - http://%(availability_zone)s.clouds.ports.ubuntu.com/ubuntu-ports/
          - http://%(region)s.clouds.ports.ubuntu.com/ubuntu-ports/
        security: []
    - arches: [default]
      failsafe:
        primary: http://ports.ubuntu.com/ubuntu-ports
        security: http://ports.ubuntu.com/ubuntu-ports
  ssh_svcname: ssh

# configure where output will go
output:
  init: "> /var/log/{{ inventory_hostname }}.log"
  config: [ ">> /tmp/{{ inventory_hostname }}.out", "> /tmp/{{ inventory_hostname }}.err" ]
  final:
    output: "| tee /tmp/{{ inventory_hostname }}.stdout | tee /tmp/{{ inventory_hostname }}.stdout"
    error: "&1"

```

### Kernel version

6.1.0-1025-rockchip

### SBC model

Turing Machines RK1

### What operating system are you seeing this problem on?

Ubuntu 24.04 LTS (Noble Nombat)

### Relevant logs

```shell

```
