### ISSUE TITLE
NanoPC-T6 | Temporary Failure in Name Resolution (DNS issue?)

### ISSUE THREAD

**Issue by Stigby** [Joshua-Riek/ubuntu-rockchip#410]
Hi everyone. I've been scratching my head with this one for a while. I've been using my NanoPC-T6 for the past three months now and it has been working great until now. 

(I had a previous issue with my T6 not booting from an NVMe, which has been resolved in issue #276)

Anyways, my current issue is somehow (maybe) related to the DNS. I have no internet connection. I've checked the DNS configuration, restarted my network service numerous times, and verified my firewall settings and router. Everything appears to be in order. I'm not sure if this is some kind of system-level issue that I'm not familiar with or if I'm just missing something. I also noticed lately that the system LED is flashing, rather than remaining a solid colour (as it did previously). Here is a list of things I've looked at and tried out:

- Checked the resolv.conf file
```
ubuntu@ubuntu:~$ sudo cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad
search .
```
- Checked the firewall (allowed ports 43 and 53, disabled UFW for now)
```
To                         Action      From
--                         ------      ----
8547/tcp                   ALLOW       192.168.100.151            # SSH
Anywhere on br-83b9fd6c736f ALLOW       172.23.0.0/16              # Sonarr
Anywhere on br-6092c7029d9c ALLOW       172.25.0.0/16              # Transmission
Anywhere on br-b4c7f7488c3b ALLOW       172.27.0.0/16              # Jellyfin
43/tcp                     ALLOW       Anywhere
53/tcp                     ALLOW       Anywhere
43/tcp (v6)                ALLOW       Anywhere (v6)
53/tcp (v6)                ALLOW       Anywhere (v6)
```
- /etc/netplan/50-cloud-init.yaml
```
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
  version: 2
  renderer: networkd
  ethernets:
    enP2p33s0:
      #dhcp4: true
      optional: true
      addresses:
        - 192.168.100.186/24
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      routes:
        - to: default
          via: 192.168.100.1
    enP4p65s0:
      #dhcp4: true
      optional: true
      addresses:
        - 192.168.100.186/24
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      routes:
        - to: default
          via: 192.168.100.1
```
- ifconfig

```
enP2p33s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 96:d1:d3:5f:5e:39  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 165

enP4p65s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.186  netmask 255.255.255.0  broadcast 192.168.100.255
        inet6 fe80::1c98:38ff:fe53:adc0  prefixlen 64  scopeid 0x20<link>
        ether 1e:98:38:53:ad:c0  txqueuelen 1000  (Ethernet)
        RX packets 12044  bytes 920291 (920.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5193  bytes 1586642 (1.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 155
```

- Update 1: Tried this also: https://stackoverflow.com/a/54460886
- Update 2: I ruled out and hardware issue as I've tried the official image from FriendlyElec (Ubuntu 22.04 with GNOME and Wayland with recommended software) and verified that I have an internet connection. (https://wiki.friendlyelec.com/wiki/index.php/NanoPC-T6#Install_OS)
- Update 3: I also tried Joshua-Riek's image. Internet connection works. I have no idea which settings I messed up. Trying to compare both images now.

Thanks in advance!
